# Generated by Django 5.0 on 2024-12-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genere',
        ),
        migrations.AddField(
            model_name='book',
            name='date_of_publish',
            field=models.DateField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genere',
            field=models.CharField(default='2022-01-01', max_length=200),
            preserve_default=False,
        ),
    ]
