# Generated by Django 5.0 on 2024-12-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_genere_book_date_of_publish_book_genere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktransaction',
            old_name='return_data',
            new_name='return_date',
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='trans_status',
            field=models.CharField(choices=[('r', 'returned'), ('i', 'issued'), ('a', 'available')], default='a', max_length=10),
        ),
    ]
